
on: [push]

jobs:
  tasks:
    # запускатись буде на віртуальній машині з найновішим ОС Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      # завантаження репозиторію на віртуальну машину
      uses: actions/checkout@v4

    - name: set up python
      # завантаження потрібної версії пайтону
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
  
    - name: install dependencies
      # завантаження залежностей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
###########################################################################
###########################################################################

    - name: task 1
      run: |
        pip install pytest
        pytest test.py
    
    - name: task 2
      # для перевірки стилю коди завантажимо flake8
      run: |
        pip install flake8
        flake8 . --count --exit-zero --statistics


