
# код для тестування взятий з іншої дисципліни 
# (технології для збору та обробки даних)
# https://github.com/dmtrDO/data/tree/main/pr-1

on: [push]

jobs:
  tasks:
    # запускатись буде на віртуальній 
    # машині з найновішим ОС Ubuntu
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # 3. Мультиверсійне тестування
        python-version: ["3.11", "3.12"]

    steps:
    - name: checkout code
      # завантаження репозиторію на віртуальну машину
      uses: actions/checkout@v4

    - name: task 3
      # завантаження потрібної версії пайтону
      uses: actions/setup-python@v4
      with:
        # 3. Мультиверсійне тестування
        python-version: ${{ matrix.python-version }}
  
    - name: install dependencies
      # завантаження залежностей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: task 1 # 1. Автоматичне тестування з Pytest
      run: |
        pip install pytest
        pytest test.py
    
    - name: task 2 # 2. Перевірка стилю коду (Linting)
      # для перевірки стилю коди завантажимо flake8
      run: |
        pip install flake8
        flake8 . --count --exit-zero --statistics

    - name: task 4 # 4. Збірка Docker-контейнера
      run : |
        docker build -t my-crawler-app .
        echo "Docker image build successfully!"
      
        
